Repository MacRoberto/pokemon.io, pull requests merged in 2025-06, with the labels that each got.

#10 Header_and_Hero
  img/Background.png
  img/Pokedex_logo.png
  index.html
  style.css
Labels: documentation

#11 Menu-Option Layout
  index.html
  main.js
  style.css
Labels: documentation

#12 Search_Bar
  .vscode/settings.json
  img/search.png
  index.html
  style.css
Labels: enhancement

#18 Footer Layout and Scripted
  img/Git_Negro.svg
  img/Instagram_Negro.svg
  img/Twitter_Negro.svg
  img/large-green-circle-3005.png
  index.html
  main.js
  style.css
Labels: enhancement

#19 About-api
  about-api.html
  img/elm.png
  img/oak.png
  index.html
  main.js
  style.css
Labels: enhancement

#22 Functionality
  .vscode/settings.json
  img/Background_red.png
  index.html
  main.js
  style.css
Labels: bug

#24 About (Pokémon)
  about-pokemon.html
  style.css
Labels: enhancement

#25 Pokemon token
  pokemon.html
  pokemon.js
  style.css
Labels: documentation
