Repository MacRoberto/pokemon.io, pull requests merged in 2025-07, with the labels that each got.

#32 side-bar fully functional
  about-api.html
  about-pokemon.html
  index.html
  main.js
  pokemon.html
  pokemon.js
  style.css
Labels: enhancement

#39 Pop Up added
  pokemon.html
  pokemon.js
  style.css
Labels: enhancement

#40 Update-pokeball-others
  style.css
Labels: bug

#41 Responsive-token-pokemon
  style.css
Labels: documentation

#42 Responsive-About-Api
  .vscode/settings.json
  about-api.html
  style.css
Labels: documentation

#45 Side-Bar Changes
  style.css
Labels: bug

#50 Poison-change-color
  pokemon.html
  style.css
Labels: bug

#53 Remove-the-sidebar
  style.css
Labels: bug

#56 Side Bar and Pop Up Hot Fixes
  style.css
Labels: enhancement

#59 Update-Responsive
  pokemon.js
  style.css
Labels: bug

#62 Pokemon-innovation-01
  style.css
Labels: documentation
